# Generated by Django 4.0.6 on 2022-07-18 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('alter_ego', models.CharField(max_length=64)),
                ('primary_ability', models.CharField(max_length=64)),
                ('secondary_ability', models.CharField(max_length=64)),
                ('catchphrase', models.CharField(max_length=128)),
                ('super_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_types.supertype')),
            ],
        ),
    ]
