# Generated by Django 4.0.6 on 2022-07-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='super',
            name='primary_ability',
        ),
        migrations.RemoveField(
            model_name='super',
            name='secondary_ability',
        ),
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.ManyToManyField(related_name='primary_ability', to='supers.power'),
        ),
        migrations.AddField(
            model_name='super',
            name='secondary_ability',
            field=models.ManyToManyField(related_name='secondary_ability', to='supers.power'),
        ),
    ]
